#! /usr/bin/env bash
set -eu

# Locate the script file.  Cross symlinks if necessary.
loc="$0"
while [ -h "$loc" ]; do
    ls=`ls -ld "$loc"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        loc="$link"  # Absolute link
    else
        loc="`dirname "$loc"`/$link"  # Relative link
    fi
done
initial_dir=$(pwd)
base_dir=$(cd "`dirname "$loc"`" && pwd)

"$base_dir/bicycle_tool/build_if_need.sh"

pushd $base_dir
    exec "$base_dir/bicycle_tool/target/start" $initial_dir "$@"
popd